version: '3.8'

services:
  app:
    image: amazoncorretto:17-alpine-jdk
    env_file:
      - .env
      - .env.local
    environment:
      DATABASE_URL: "jdbc:postgresql://db:${BOT_TKT_DB_PORT}/${BOT_TKT_DB_NAME}"
      DATABASE_USERNAME: ${BOT_TKT_DB_USER}
      DATABASE_PASSWORD: ${BOT_TKT_DB_PASS}
    networks:
      - infra_net
    depends_on:
      - db
    volumes:
      - ./:/app
    entrypoint: ['sh', '/app/entrypoint.sh']
  db:
    image: sameersbn/postgresql:12-20200524
    ports:
      - "${BOT_TKT_DB_PORT}:5432"
    environment:
      DB_NAME: ${BOT_TKT_DB_NAME}
      DB_USER: ${BOT_TKT_DB_USER}
      DB_PASS: ${BOT_TKT_DB_PASS}
    networks:
      - infra_net
    volumes:
      - db-storage:/var/lib/postgresql
volumes:
  db-storage:
networks:
  infra_net: