version: '3.8'

services:
  app:
    image: amazoncorretto:17-alpine-jdk
    restart: always
    environment:
      - BOT_TKT_TG_TOKEN
      - TG_BOT_TOKEN=${BOT_TKT_TG_TOKEN}
      - DATABASE_URL=${BOT_TKT_DATABASE_URL}
      - DATABASE_USERNAME=${BOT_TKT_DATABASE_USERNAME}
      - DATABASE_PASSWORD=${BOT_TKT_DATABASE_PASSWORD}
    networks:
      - infra_net
    depends_on:
      - db
    volumes:
      - ./:/app
    entrypoint: ['sh', '/app/entrypoint.sh']
  db:
    image: sameersbn/postgresql:12-20200524
    ports:
      - "5432:5432"
    environment:
      - DB_NAME=${BOT_TKT_DB_NAME}
      - DB_USER=${BOT_TKT_DATABASE_USERNAME}
      - DB_PASS=${BOT_TKT_DATABASE_PASSWORD}
      - TG_BOT_TOKEN=${BOT_TKT_TG_BOT_TOKEN}
    networks:
      - infra_net
    volumes:
      - db-storage:/var/lib/postgresql
volumes:
  db-storage:
networks:
  infra_net: